/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateImageArgs } from "./CreateImageArgs";
import { UpdateImageArgs } from "./UpdateImageArgs";
import { DeleteImageArgs } from "./DeleteImageArgs";
import { ImageCountArgs } from "./ImageCountArgs";
import { ImageFindManyArgs } from "./ImageFindManyArgs";
import { ImageFindUniqueArgs } from "./ImageFindUniqueArgs";
import { Image } from "./Image";
import { Job } from "../../job/base/Job";
import { ImageService } from "../image.service";
@graphql.Resolver(() => Image)
export class ImageResolverBase {
  constructor(protected readonly service: ImageService) {}

  async _imagesMeta(
    @graphql.Args() args: ImageCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Image])
  async images(@graphql.Args() args: ImageFindManyArgs): Promise<Image[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Image, { nullable: true })
  async image(
    @graphql.Args() args: ImageFindUniqueArgs
  ): Promise<Image | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Image)
  async createImage(@graphql.Args() args: CreateImageArgs): Promise<Image> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        job: {
          connect: args.data.job,
        },
      },
    });
  }

  @graphql.Mutation(() => Image)
  async updateImage(
    @graphql.Args() args: UpdateImageArgs
  ): Promise<Image | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          job: {
            connect: args.data.job,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Image)
  async deleteImage(
    @graphql.Args() args: DeleteImageArgs
  ): Promise<Image | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Job, {
    nullable: true,
    name: "job",
  })
  async resolveFieldJob(@graphql.Parent() parent: Image): Promise<Job | null> {
    const result = await this.service.getJob(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
