/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MarketService } from "../market.service";
import { MarketCreateInput } from "./MarketCreateInput";
import { MarketWhereInput } from "./MarketWhereInput";
import { MarketWhereUniqueInput } from "./MarketWhereUniqueInput";
import { MarketFindManyArgs } from "./MarketFindManyArgs";
import { MarketUpdateInput } from "./MarketUpdateInput";
import { Market } from "./Market";
import { CityFindManyArgs } from "../../city/base/CityFindManyArgs";
import { City } from "../../city/base/City";
import { CityWhereUniqueInput } from "../../city/base/CityWhereUniqueInput";

export class MarketControllerBase {
  constructor(protected readonly service: MarketService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Market })
  async create(@common.Body() data: MarketCreateInput): Promise<Market> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Market] })
  @ApiNestedQuery(MarketFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Market[]> {
    const args = plainToClass(MarketFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Market })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: MarketWhereUniqueInput
  ): Promise<Market | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Market })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: MarketWhereUniqueInput,
    @common.Body() data: MarketUpdateInput
  ): Promise<Market | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Market })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: MarketWhereUniqueInput
  ): Promise<Market | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/cities")
  @ApiNestedQuery(CityFindManyArgs)
  async findManyCities(
    @common.Req() request: Request,
    @common.Param() params: MarketWhereUniqueInput
  ): Promise<City[]> {
    const query = plainToClass(CityFindManyArgs, request.query);
    const results = await this.service.findCities(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        market: {
          select: {
            id: true,
          },
        },

        name: true,
        roofingMaterialIds: true,
        state: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/cities")
  async connectCities(
    @common.Param() params: MarketWhereUniqueInput,
    @common.Body() body: CityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cities: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/cities")
  async updateCities(
    @common.Param() params: MarketWhereUniqueInput,
    @common.Body() body: CityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cities: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/cities")
  async disconnectCities(
    @common.Param() params: MarketWhereUniqueInput,
    @common.Body() body: CityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      cities: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
