/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateMarketArgs } from "./CreateMarketArgs";
import { UpdateMarketArgs } from "./UpdateMarketArgs";
import { DeleteMarketArgs } from "./DeleteMarketArgs";
import { MarketCountArgs } from "./MarketCountArgs";
import { MarketFindManyArgs } from "./MarketFindManyArgs";
import { MarketFindUniqueArgs } from "./MarketFindUniqueArgs";
import { Market } from "./Market";
import { CityFindManyArgs } from "../../city/base/CityFindManyArgs";
import { City } from "../../city/base/City";
import { MarketService } from "../market.service";
@graphql.Resolver(() => Market)
export class MarketResolverBase {
  constructor(protected readonly service: MarketService) {}

  async _marketsMeta(
    @graphql.Args() args: MarketCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Market])
  async markets(@graphql.Args() args: MarketFindManyArgs): Promise<Market[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Market, { nullable: true })
  async market(
    @graphql.Args() args: MarketFindUniqueArgs
  ): Promise<Market | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Market)
  async createMarket(@graphql.Args() args: CreateMarketArgs): Promise<Market> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Market)
  async updateMarket(
    @graphql.Args() args: UpdateMarketArgs
  ): Promise<Market | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Market)
  async deleteMarket(
    @graphql.Args() args: DeleteMarketArgs
  ): Promise<Market | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [City], { name: "cities" })
  async resolveFieldCities(
    @graphql.Parent() parent: Market,
    @graphql.Args() args: CityFindManyArgs
  ): Promise<City[]> {
    const results = await this.service.findCities(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
