/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateCityArgs } from "./CreateCityArgs";
import { UpdateCityArgs } from "./UpdateCityArgs";
import { DeleteCityArgs } from "./DeleteCityArgs";
import { CityCountArgs } from "./CityCountArgs";
import { CityFindManyArgs } from "./CityFindManyArgs";
import { CityFindUniqueArgs } from "./CityFindUniqueArgs";
import { City } from "./City";
import { Market } from "../../market/base/Market";
import { CityService } from "../city.service";
@graphql.Resolver(() => City)
export class CityResolverBase {
  constructor(protected readonly service: CityService) {}

  async _citiesMeta(
    @graphql.Args() args: CityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [City])
  async cities(@graphql.Args() args: CityFindManyArgs): Promise<City[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => City, { nullable: true })
  async city(@graphql.Args() args: CityFindUniqueArgs): Promise<City | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => City)
  async createCity(@graphql.Args() args: CreateCityArgs): Promise<City> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        market: {
          connect: args.data.market,
        },
      },
    });
  }

  @graphql.Mutation(() => City)
  async updateCity(@graphql.Args() args: UpdateCityArgs): Promise<City | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          market: {
            connect: args.data.market,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => City)
  async deleteCity(@graphql.Args() args: DeleteCityArgs): Promise<City | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Market, {
    nullable: true,
    name: "market",
  })
  async resolveFieldMarket(
    @graphql.Parent() parent: City
  ): Promise<Market | null> {
    const result = await this.service.getMarket(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
