/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreatePricingArgs } from "./CreatePricingArgs";
import { UpdatePricingArgs } from "./UpdatePricingArgs";
import { DeletePricingArgs } from "./DeletePricingArgs";
import { PricingCountArgs } from "./PricingCountArgs";
import { PricingFindManyArgs } from "./PricingFindManyArgs";
import { PricingFindUniqueArgs } from "./PricingFindUniqueArgs";
import { Pricing } from "./Pricing";
import { OfficeLocation } from "../../officeLocation/base/OfficeLocation";
import { PricingService } from "../pricing.service";
@graphql.Resolver(() => Pricing)
export class PricingResolverBase {
  constructor(protected readonly service: PricingService) {}

  async _pricingsMeta(
    @graphql.Args() args: PricingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Pricing])
  async pricings(
    @graphql.Args() args: PricingFindManyArgs
  ): Promise<Pricing[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Pricing, { nullable: true })
  async pricing(
    @graphql.Args() args: PricingFindUniqueArgs
  ): Promise<Pricing | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Pricing)
  async createPricing(
    @graphql.Args() args: CreatePricingArgs
  ): Promise<Pricing> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        officeLocation: {
          connect: args.data.officeLocation,
        },
      },
    });
  }

  @graphql.Mutation(() => Pricing)
  async updatePricing(
    @graphql.Args() args: UpdatePricingArgs
  ): Promise<Pricing | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          officeLocation: {
            connect: args.data.officeLocation,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Pricing)
  async deletePricing(
    @graphql.Args() args: DeletePricingArgs
  ): Promise<Pricing | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => OfficeLocation, {
    nullable: true,
    name: "officeLocation",
  })
  async resolveFieldOfficeLocation(
    @graphql.Parent() parent: Pricing
  ): Promise<OfficeLocation | null> {
    const result = await this.service.getOfficeLocation(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
