/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BidService } from "../bid.service";
import { BidCreateInput } from "./BidCreateInput";
import { BidWhereInput } from "./BidWhereInput";
import { BidWhereUniqueInput } from "./BidWhereUniqueInput";
import { BidFindManyArgs } from "./BidFindManyArgs";
import { BidUpdateInput } from "./BidUpdateInput";
import { Bid } from "./Bid";
import { LineItemFindManyArgs } from "../../lineItem/base/LineItemFindManyArgs";
import { LineItem } from "../../lineItem/base/LineItem";
import { LineItemWhereUniqueInput } from "../../lineItem/base/LineItemWhereUniqueInput";

export class BidControllerBase {
  constructor(protected readonly service: BidService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Bid })
  async create(@common.Body() data: BidCreateInput): Promise<Bid> {
    return await this.service.create({
      data: {
        ...data,

        job: {
          connect: data.job,
        },
      },
      select: {
        companyId: true,
        createdAt: true,
        id: true,

        job: {
          select: {
            id: true,
          },
        },

        quoteUrl: true,
        startDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Bid] })
  @ApiNestedQuery(BidFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Bid[]> {
    const args = plainToClass(BidFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        companyId: true,
        createdAt: true,
        id: true,

        job: {
          select: {
            id: true,
          },
        },

        quoteUrl: true,
        startDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Bid })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: BidWhereUniqueInput
  ): Promise<Bid | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        companyId: true,
        createdAt: true,
        id: true,

        job: {
          select: {
            id: true,
          },
        },

        quoteUrl: true,
        startDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Bid })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: BidWhereUniqueInput,
    @common.Body() data: BidUpdateInput
  ): Promise<Bid | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          job: {
            connect: data.job,
          },
        },
        select: {
          companyId: true,
          createdAt: true,
          id: true,

          job: {
            select: {
              id: true,
            },
          },

          quoteUrl: true,
          startDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Bid })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: BidWhereUniqueInput
  ): Promise<Bid | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          companyId: true,
          createdAt: true,
          id: true,

          job: {
            select: {
              id: true,
            },
          },

          quoteUrl: true,
          startDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/lineItems")
  @ApiNestedQuery(LineItemFindManyArgs)
  async findManyLineItems(
    @common.Req() request: Request,
    @common.Param() params: BidWhereUniqueInput
  ): Promise<LineItem[]> {
    const query = plainToClass(LineItemFindManyArgs, request.query);
    const results = await this.service.findLineItems(params.id, {
      ...query,
      select: {
        bid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        details: true,
        id: true,
        price: true,
        roofingTypeId: true,
        updatedAt: true,
        wasteFactor: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/lineItems")
  async connectLineItems(
    @common.Param() params: BidWhereUniqueInput,
    @common.Body() body: LineItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lineItems: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/lineItems")
  async updateLineItems(
    @common.Param() params: BidWhereUniqueInput,
    @common.Body() body: LineItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lineItems: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/lineItems")
  async disconnectLineItems(
    @common.Param() params: BidWhereUniqueInput,
    @common.Body() body: LineItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lineItems: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
